# Use Eclipse Temurin for Java 17 (more reliable than the old openjdk image)
FROM eclipse-temurin:17-jdk-focal

# Set the working directory
WORKDIR /app

# Copy the jar file generated by Maven
COPY target/food-delivery-app-1.0-SNAPSHOT.jar app.jar

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
